package vistas;

import AccesoADatos.AlumnoData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Entidades.Alumno;

public class ListarAlumnosView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;//ninguna celda es editable
        }
    };

    public ListarAlumnosView() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluXmat = new javax.swing.JTable();

        jLabel5.setText("jLabel5");

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(910, 696));

        jPanel1.setBackground(new java.awt.Color(223, 232, 225));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(2, 64, 126));

        jLabel1.setBackground(new java.awt.Color(2, 64, 126));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTAR ALUMNOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 40);

        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 90, 47, 16);

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 160, 48, 16);

        jTapellido.setBackground(new java.awt.Color(230, 244, 245));
        jTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTapellidoKeyReleased(evt);
            }
        });
        jPanel1.add(jTapellido);
        jTapellido.setBounds(250, 90, 220, 28);

        jTnombre.setBackground(new java.awt.Color(230, 244, 245));
        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnombreKeyReleased(evt);
            }
        });
        jPanel1.add(jTnombre);
        jTnombre.setBounds(250, 160, 220, 28);

        jTableAluXmat.setBackground(new java.awt.Color(230, 244, 245));
        jTableAluXmat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAluXmat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 250, 780, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellidoKeyReleased
        jTnombre.setText("");

        AlumnoData alumno = new AlumnoData();
        List<Alumno> lista = new ArrayList<Alumno>();
        lista = alumno.listarAlumnos();
        borrarFilas();
        for (Alumno alu : lista) {
            if (alu.getApellido().toLowerCase().startsWith(jTapellido.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    alu.getApellido(),
                    alu.getNombre(),
                    alu.getDni(),
                    alu.getId(),});

            }
        }
    }//GEN-LAST:event_jTapellidoKeyReleased

    private void jTnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyReleased
        jTapellido.setText("");
        borrarFilas();
        AlumnoData alumno = new AlumnoData();
        List<Alumno> lista = new ArrayList<Alumno>();
        lista = alumno.listarAlumnos();
        for (Alumno alu : lista) {
            if (alu.getNombre().toLowerCase().startsWith(jTnombre.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    alu.getApellido(),
                    alu.getNombre(),
                    alu.getDni(),
                    alu.getId(),});

            }
        }
    }//GEN-LAST:event_jTnombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAluXmat;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");
        modelo.addColumn("ID");
        jTableAluXmat.setModel(modelo);

    }

    private void borrarFilas() {

        int filas = jTableAluXmat.getRowCount() - 1;

        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }

    }

}
