/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodri
 */
public class RegistroView extends javax.swing.JFrame {

    private final ImageIcon imgOjoOn = new ImageIcon(getClass().getResource("/imagenes/ojoOn.png"));
    private final ImageIcon imgOjoOff = new ImageIcon(getClass().getResource("/imagenes/ojoOff.png"));
    private JFrame ventana;

    private final ImageIcon imgCorrecto = new ImageIcon(getClass().getResource("/imagenes/tilde.png"));
    private final ImageIcon imgIncorrecto = new ImageIcon(getClass().getResource("/imagenes/incorrecto.png"));

    /**
     * Creates new form LoginView
     */
    public RegistroView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    public RegistroView(JFrame ventana) {
        this.ventana = ventana;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        labelCheckUsuario.setIcon(null);
        labelCheckClave.setIcon(null);
        labelCheckRepetirClave.setIcon(null);
        calendario.setLocation(400, 400);
        calendario.setVisible(false);
        ventana.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelLinea = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        panelDerecha = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelTipoCuenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonOjo = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        labelDni = new javax.swing.JLabel();
        labelFechaNac = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        textFecha = new javax.swing.JTextField();
        labelRepetirClave = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        textCoreo = new javax.swing.JTextField();
        textUsuario = new javax.swing.JTextField();
        passwordFieldRepetir = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        labelUsuario = new javax.swing.JLabel();
        labelClave = new javax.swing.JLabel();
        labelCheckUsuario = new javax.swing.JLabel();
        labelCheckRepetirClave = new javax.swing.JLabel();
        labelCheckClave = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        botonCalendario = new javax.swing.JButton();
        comboBoxTipoCuenta = new javax.swing.JComboBox<>();
        labelCodigo = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelFondo.setBackground(new java.awt.Color(230, 244, 245));
        panelFondo.setBorder(null);
        panelFondo.setMinimumSize(new java.awt.Dimension(750, 500));
        panelFondo.setPreferredSize(new java.awt.Dimension(750, 500));
        panelFondo.setLayout(null);

        labelLinea.setBackground(new java.awt.Color(59, 99, 133));
        labelLinea.setOpaque(true);
        panelFondo.add(labelLinea);
        labelLinea.setBounds(95, 50, 260, 2);
        panelFondo.add(calendario);
        calendario.setBounds(360, 300, 420, 240);

        panelDerecha.setBackground(new java.awt.Color(59, 99, 133));
        panelDerecha.setLayout(null);

        botonCerrar.setBackground(new java.awt.Color(59, 99, 133));
        botonCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrar.setText("X");
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setOpaque(true);
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonCerrarMouseReleased(evt);
            }
        });
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        panelDerecha.add(botonCerrar);
        botonCerrar.setBounds(400, 10, 40, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ulpLogotipoBlanco.png"))); // NOI18N
        panelDerecha.add(jLabel1);
        jLabel1.setBounds(0, 200, 450, 300);

        panelFondo.add(panelDerecha);
        panelDerecha.setBounds(450, 0, 450, 700);

        labelTipoCuenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTipoCuenta.setForeground(new java.awt.Color(59, 99, 133));
        labelTipoCuenta.setText("Tipo de cuenta");
        panelFondo.add(labelTipoCuenta);
        labelTipoCuenta.setBounds(95, 545, 170, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 99, 133));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRARSE");
        panelFondo.add(jLabel3);
        jLabel3.setBounds(95, 10, 260, 40);

        botonOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoOff.png"))); // NOI18N
        botonOjo.setBorderPainted(false);
        botonOjo.setContentAreaFilled(false);
        botonOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOjoActionPerformed(evt);
            }
        });
        panelFondo.add(botonOjo);
        botonOjo.setBounds(320, 440, 32, 30);

        textNombre.setBackground(new java.awt.Color(254, 254, 254));
        textNombre.setForeground(new java.awt.Color(153, 153, 153));
        textNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNombre.setText("Ingrese su nombre");
        textNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNombreFocusLost(evt);
            }
        });
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        textNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombreKeyTyped(evt);
            }
        });
        panelFondo.add(textNombre);
        textNombre.setBounds(95, 80, 260, 30);

        labelNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(59, 99, 133));
        labelNombre.setText("Nombre completo");
        panelFondo.add(labelNombre);
        labelNombre.setBounds(95, 65, 170, 15);

        textApellido.setBackground(new java.awt.Color(254, 254, 254));
        textApellido.setForeground(new java.awt.Color(153, 153, 153));
        textApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textApellido.setText("Ingrese su apellido");
        textApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textApellidoFocusLost(evt);
            }
        });
        textApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoActionPerformed(evt);
            }
        });
        textApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textApellidoKeyTyped(evt);
            }
        });
        panelFondo.add(textApellido);
        textApellido.setBounds(95, 140, 260, 30);

        labelApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelApellido.setForeground(new java.awt.Color(59, 99, 133));
        labelApellido.setText("Apellido");
        panelFondo.add(labelApellido);
        labelApellido.setBounds(95, 125, 170, 15);

        labelDni.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelDni.setForeground(new java.awt.Color(59, 99, 133));
        labelDni.setText("N° de Documento");
        panelFondo.add(labelDni);
        labelDni.setBounds(95, 185, 170, 15);

        labelFechaNac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelFechaNac.setForeground(new java.awt.Color(59, 99, 133));
        labelFechaNac.setText("Fecha de Nacimiento");
        panelFondo.add(labelFechaNac);
        labelFechaNac.setBounds(95, 245, 170, 15);

        labelEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(59, 99, 133));
        labelEmail.setText("Correo electrónico");
        panelFondo.add(labelEmail);
        labelEmail.setBounds(95, 305, 170, 15);

        textDni.setBackground(new java.awt.Color(254, 254, 254));
        textDni.setForeground(new java.awt.Color(153, 153, 153));
        textDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDni.setText("Ingrese su DNI");
        textDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDniFocusLost(evt);
            }
        });
        textDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDniActionPerformed(evt);
            }
        });
        textDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDniKeyTyped(evt);
            }
        });
        panelFondo.add(textDni);
        textDni.setBounds(95, 200, 260, 30);

        textFecha.setEditable(false);
        textFecha.setBackground(new java.awt.Color(254, 254, 254));
        textFecha.setForeground(new java.awt.Color(153, 153, 153));
        textFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFecha.setText("Seleccione una fecha");
        textFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFechaFocusLost(evt);
            }
        });
        textFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaActionPerformed(evt);
            }
        });
        textFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechaKeyTyped(evt);
            }
        });
        panelFondo.add(textFecha);
        textFecha.setBounds(95, 260, 260, 30);

        labelRepetirClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelRepetirClave.setForeground(new java.awt.Color(59, 99, 133));
        labelRepetirClave.setText("Repetir contraseña");
        panelFondo.add(labelRepetirClave);
        labelRepetirClave.setBounds(95, 485, 170, 15);

        textCodigo.setBackground(new java.awt.Color(254, 254, 254));
        textCodigo.setForeground(new java.awt.Color(153, 153, 153));
        textCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCodigo.setText("Ingrese su Id de alumno");
        textCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCodigoFocusLost(evt);
            }
        });
        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });
        textCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodigoKeyTyped(evt);
            }
        });
        panelFondo.add(textCodigo);
        textCodigo.setBounds(95, 610, 260, 30);

        textCoreo.setBackground(new java.awt.Color(254, 254, 254));
        textCoreo.setForeground(new java.awt.Color(153, 153, 153));
        textCoreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCoreo.setText("Ingrese su email");
        textCoreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCoreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCoreoFocusLost(evt);
            }
        });
        textCoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCoreoActionPerformed(evt);
            }
        });
        textCoreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCoreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCoreoKeyTyped(evt);
            }
        });
        panelFondo.add(textCoreo);
        textCoreo.setBounds(95, 320, 260, 30);

        textUsuario.setBackground(new java.awt.Color(254, 254, 254));
        textUsuario.setForeground(new java.awt.Color(153, 153, 153));
        textUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textUsuario.setText("Elija un nombre de usuario");
        textUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textUsuarioFocusLost(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        textUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUsuarioKeyTyped(evt);
            }
        });
        panelFondo.add(textUsuario);
        textUsuario.setBounds(95, 380, 260, 30);

        passwordFieldRepetir.setForeground(new java.awt.Color(153, 153, 153));
        passwordFieldRepetir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordFieldRepetir.setText("Repita  su contraseña");
        panelFondo.add(passwordFieldRepetir);
        passwordFieldRepetir.setBounds(95, 500, 260, 30);

        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("Ingrese su Contraseña");
        panelFondo.add(passwordField);
        passwordField.setBounds(95, 440, 260, 30);

        labelUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(59, 99, 133));
        labelUsuario.setText("Nombre de usuario");
        panelFondo.add(labelUsuario);
        labelUsuario.setBounds(95, 365, 170, 15);

        labelClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelClave.setForeground(new java.awt.Color(59, 99, 133));
        labelClave.setText("Contraseña");
        panelFondo.add(labelClave);
        labelClave.setBounds(95, 425, 170, 15);

        labelCheckUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tilde.png"))); // NOI18N
        panelFondo.add(labelCheckUsuario);
        labelCheckUsuario.setBounds(370, 380, 30, 30);

        labelCheckRepetirClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incorrecto.png"))); // NOI18N
        panelFondo.add(labelCheckRepetirClave);
        labelCheckRepetirClave.setBounds(370, 500, 30, 30);

        labelCheckClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incorrecto.png"))); // NOI18N
        panelFondo.add(labelCheckClave);
        labelCheckClave.setBounds(370, 440, 30, 30);

        botonRegistrarse.setBackground(new java.awt.Color(59, 99, 133));
        botonRegistrarse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarse.setText("REGISTRARSE");
        botonRegistrarse.setContentAreaFilled(false);
        botonRegistrarse.setOpaque(true);
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseExited(evt);
            }
        });
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });
        panelFondo.add(botonRegistrarse);
        botonRegistrarse.setBounds(100, 660, 260, 30);

        botonCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        botonCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendarioActionPerformed(evt);
            }
        });
        panelFondo.add(botonCalendario);
        botonCalendario.setBounds(360, 260, 30, 30);

        comboBoxTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Administrativo" }));
        panelFondo.add(comboBoxTipoCuenta);
        comboBoxTipoCuenta.setBounds(95, 560, 260, 26);

        labelCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(59, 99, 133));
        labelCodigo.setText("Codigo de identificación");
        panelFondo.add(labelCodigo);
        labelCodigo.setBounds(95, 595, 170, 15);

        botonRegresar.setBackground(new java.awt.Color(230, 244, 245));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setOpaque(true);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        panelFondo.add(botonRegresar);
        botonRegresar.setBounds(10, 10, 40, 40);

        getContentPane().add(panelFondo);
        panelFondo.setBounds(0, 0, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOjoActionPerformed
        if (botonOjo.getIcon().equals(imgOjoOn)) {
            botonOjo.setIcon(imgOjoOff);
            passwordField.setEchoChar('*');

        } else {
            botonOjo.setIcon(imgOjoOn);
            passwordField.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_botonOjoActionPerformed

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        botonCerrar.setBackground(new Color(170, 194, 205));
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        botonCerrar.setBackground(new Color(59, 99, 133));
    }//GEN-LAST:event_botonCerrarMouseExited

    private void botonCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMousePressed
        botonCerrar.setBackground(new Color(59, 99, 133));
    }//GEN-LAST:event_botonCerrarMousePressed

    private void botonCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseReleased
        botonCerrar.setBackground(new Color(59, 99, 133));
    }//GEN-LAST:event_botonCerrarMouseReleased

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        ventana.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void textNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreFocusGained

    private void textNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreFocusLost

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreKeyReleased

    private void textNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreKeyTyped

    private void textApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textApellidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoFocusGained

    private void textApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoFocusLost

    private void textApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoActionPerformed

    private void textApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textApellidoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoKeyReleased

    private void textApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textApellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoKeyTyped

    private void textDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDniFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniFocusGained

    private void textDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniFocusLost

    private void textDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniActionPerformed

    private void textDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDniKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniKeyReleased

    private void textDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDniKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniKeyTyped

    private void textFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFechaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaFocusGained

    private void textFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFechaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaFocusLost

    private void textFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaActionPerformed

    private void textFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaKeyReleased

    private void textFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaKeyTyped

    private void textCoreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCoreoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textCoreoFocusGained

    private void textCoreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCoreoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textCoreoFocusLost

    private void textCoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCoreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCoreoActionPerformed

    private void textCoreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCoreoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textCoreoKeyReleased

    private void textCoreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCoreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCoreoKeyTyped

    private void textUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioFocusGained

    private void textUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioFocusLost

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioKeyReleased

    private void textUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioKeyTyped

    private void botonRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseEntered
        botonRegistrarse.setBackground(new Color(170, 194, 205));
    }//GEN-LAST:event_botonRegistrarseMouseEntered

    private void botonRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseExited
        botonRegistrarse.setBackground(new Color(59, 99, 133));
    }//GEN-LAST:event_botonRegistrarseMouseExited

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        if (textNombre.getText().equals("Ingrese su nombre")
                || textApellido.getText().equals("Ingrese su apellido")
                || textDni.getText().equals("Ingrese su DNI")
                || textFecha.getText().equals("Seleccione una fecha")
                || textCoreo.getText().equals("Ingrese su email")
                || textUsuario.getText().equals("Elija un nombre de usuario")
                || passwordField.getText().equals("Ingrese su contraseña")
                || !passwordFieldRepetir.getText().equals(passwordField.getText())) {
            JOptionPane.showMessageDialog(this, "Complete todos los datos", "Hay campos vacíos", 0);
        }
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalendarioActionPerformed
        if (calendario.isVisible()) {
            calendario.setVisible(false);
        } else {
            calendario.setVisible(true);
        }
    }//GEN-LAST:event_botonCalendarioActionPerformed

    private void textCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoFocusGained

    private void textCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoFocusLost

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void textCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoKeyReleased

    private void textCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoKeyTyped

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
       // botonRegresar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        //botonRegresar.setBackground(new Color(230, 244, 245));
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        new LoginView(ventana).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalendario;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonOjo;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JButton botonRegresar;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> comboBoxTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCheckClave;
    private javax.swing.JLabel labelCheckRepetirClave;
    private javax.swing.JLabel labelCheckUsuario;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelLinea;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRepetirClave;
    private javax.swing.JLabel labelTipoCuenta;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordFieldRepetir;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textCoreo;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textFecha;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
